---
server:
  contextPath: /booking-service
  port: 7000

spring:
  jackson:
    serialization-inclusion: non_null
  jpa:
    generate-ddl: true
  h2:
    console.enabled: true

logging:
  level:
    root: INFO
---